#!/usr/bin/env python3
"""Render the Developer Guide's API reference from the shipping integration.

The page this writes is not authored anywhere. Its structure comes from
``custom_components/example_integration/api_surface.py`` — the model the runtime itself
consumes — and every human-readable string comes from ``services.yaml`` and
``strings.json``, the same two files Home Assistant reads to label the service
dialog, the automation editor and the options form. So the reference and the
Home Assistant UI cannot describe an action differently: there is one string, and
both render it.

Output goes to ``website/developer/api.md``, which is generated and gitignored
along with the rest of that tree, so nothing here can go stale in git. It runs
from ``npm run sync`` (and therefore from ``npm start`` / ``npm run build``),
*after* ``sync-docs.mjs``, which clears that directory first.

Run it by hand with::

    python3 ci/generate_api_docs.py            # write website/developer/api.md
    python3 ci/generate_api_docs.py --stdout   # print instead, for a quick look
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
import types
from pathlib import Path
from types import ModuleType
from typing import Any, NamedTuple

ROOT = Path(__file__).resolve().parent.parent
COMPONENT = ROOT / "custom_components" / "example_integration"
DEFAULT_OUT = ROOT / "website" / "developer" / "api.md"

# Kept in step with the entry in website/scripts/doc-map.mjs, which tells the
# PR-preview comment where this page lives. tests/unit/test_generate_api_docs.py
# compares the two so they can't drift.
PAGE_TITLE = "API reference"
PAGE_POSITION = 2

# `scripts/rename.py --repo OWNER/NAME` rewrites this URL.
_SITE = "https://prestomation.github.io/ha-integration-template"

_BANNER = (
    "<!-- Generated by ci/generate_api_docs.py from api_surface.py, services.yaml\n"
    "     and strings.json. Do not edit: this file is not in git. -->"
)

_STATUS_LABELS = {
    "published": "Published",
    "internal": "Internal",
    "not_applicable": "Not applicable",
    "deferred": "Deferred",
}

_RESPONSE_LABELS = {
    "optional": "Can return a response",
    "only": "Returns a response",
}


class Sources(NamedTuple):
    """Everything the renderer reads, so tests can substitute their own."""

    surface: ModuleType
    services_yaml: dict[str, Any]
    strings: dict[str, Any]


# ── Loading ──────────────────────────────────────────────────────────────────


def load_surface(component: Path = COMPONENT) -> ModuleType:
    """Return the ``api_surface`` module without importing Home Assistant.

    Under pytest the root ``conftest.py`` has already executed the pure core, so
    reuse its module object rather than loading a second copy. Standalone, load
    ``api_surface`` and the pure modules it imports by path under stub parent
    packages — the same trick, and for the same reason: the real package
    ``__init__.py`` imports Home Assistant, which is not installed here.
    """
    pkg = "custom_components.example_integration"
    if (loaded := sys.modules.get(f"{pkg}.api_surface")) is not None:
        return loaded

    for name, path in ((("custom_components"), component.parent), (pkg, component)):
        if name not in sys.modules:
            stub = types.ModuleType(name)
            stub.__path__ = [str(path)]  # type: ignore[attr-defined]
            sys.modules[name] = stub

    # ``api_surface`` imports only ``const``, which imports nothing — that is what
    # lets this run on a docs runner with none of the integration's dependencies
    # installed. ``test_api_surface_imports_stay_light`` keeps it that way, so this
    # list cannot silently fall behind.
    for name in ("const", "api_surface"):
        if f"{pkg}.{name}" in sys.modules:
            continue
        spec = importlib.util.spec_from_file_location(
            f"{pkg}.{name}", str(component / f"{name}.py")
        )
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        sys.modules[f"{pkg}.{name}"] = module
        spec.loader.exec_module(module)
    return sys.modules[f"{pkg}.api_surface"]


def load_sources(component: Path = COMPONENT) -> Sources:
    """Read the model and the two string files it resolves its prose from."""
    import yaml  # imported lazily: only the generator needs PyYAML

    return Sources(
        surface=load_surface(component),
        services_yaml=yaml.safe_load(
            (component / "services.yaml").read_text(encoding="utf-8")
        ),
        strings=json.loads((component / "strings.json").read_text(encoding="utf-8")),
    )


# ── Markdown helpers ─────────────────────────────────────────────────────────


def cell(text: Any) -> str:
    """Return *text* safe to drop into a Markdown table cell.

    A cell is one line, so folded YAML descriptions collapse to spaces, and a
    literal pipe (``str | None`` is a whole column of them) has to be escaped or
    it ends the cell early.
    """
    if text is None:
        return ""
    return " ".join(str(text).split()).replace("|", r"\|")


def selector_summary(selector: Any) -> str:
    """Summarize a ``services.yaml`` selector the way the UI would offer it.

    The selector is what decides the widget a user sees in the service dialog, so
    it belongs in a reference an automation author reads — but its raw YAML is
    noise. Render the shape and the constraints that change what you can pass.
    """
    if not isinstance(selector, dict) or not selector:
        return ""
    kind, config = next(iter(selector.items()))
    config = config or {}
    if kind == "select":
        options = config.get("options") or []
        names = [o["value"] if isinstance(o, dict) else o for o in options]
        return f"select ({', '.join(str(n) for n in names)})" if names else "select"
    if kind == "number":
        bounds = []
        if "min" in config:
            bounds.append(f"min {config['min']}")
        if "max" in config:
            bounds.append(f"max {config['max']}")
        return f"number ({', '.join(bounds)})" if bounds else "number"
    if kind == "text" and config.get("multiline"):
        return "text (multiline)"
    if config.get("multiple"):
        return f"{kind} (multiple)"
    return str(kind)


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    if not rows:
        return []
    return [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
        *["| " + " | ".join(row) + " |" for row in rows],
        "",
    ]


def _fields_table(fields: Any) -> list[str]:
    """Render modelled :class:`Field` rows, dropping the columns nobody filled."""
    rows = [
        [f"`{f.name}`", f"`{cell(f.type)}`" if f.type else "", cell(f.note)]
        for f in fields
    ]
    if not any(row[2] for row in rows):
        return _table(["Field", "Type"], [row[:2] for row in rows])
    return _table(["Field", "Type", "Notes"], rows)


# ── Sections ─────────────────────────────────────────────────────────────────


def render_surface_coverage(sources: Sources) -> list[str]:
    surface = sources.surface
    return [
        "## Surface coverage",
        "",
        "Every kind of integration surface Home Assistant offers, and the status of",
        "each one here. The rows that say *not applicable* or *deferred* are the",
        "useful ones: a list of what exists cannot tell you what is missing.",
        "",
        *_table(
            ["Surface", "Status", "Notes"],
            [
                [cell(spec.kind), _STATUS_LABELS[spec.status], cell(spec.note)]
                for spec in surface.SURFACE_KINDS
            ],
        ),
    ]


def render_services(sources: Sources) -> list[str]:
    """One section per action, labelled exactly as the service dialog labels it."""
    surface, yaml_doc, strings = sources
    lines = [
        "## Actions",
        "",
        "Every operation that changes or exports data is a Home Assistant action,",
        "so automations, scripts, voice assistants and other integrations all",
        "reach it the same way. Guard each call with",
        '`hass.services.has_service("example_integration", "<action>")` so your',
        "integration still works when this one is not installed.",
        "",
    ]
    for spec in surface.SERVICES:
        localized = strings.get("services", {}).get(spec.name, {})
        described = yaml_doc.get(spec.name) or {}
        badges = []
        if spec.admin_only:
            badges.append("**Admin only**")
        if label := _RESPONSE_LABELS.get(spec.response):
            badges.append(f"**{label}**")

        lines += [f"### `example_integration.{spec.name}`", ""]
        if title := localized.get("name"):
            lines += [f"*{cell(title)}*", ""]
        if description := localized.get("description"):
            lines += [cell(description), ""]
        if badges:
            lines += [" · ".join(badges), ""]

        rows = []
        for field, config in (described.get("fields") or {}).items():
            config = config or {}
            field_strings = localized.get("fields", {}).get(field, {})
            # Required rides in the name cell rather than a column of its own: a
            # fifth column pushes the descriptions past the content width, and
            # Docusaurus answers that with a horizontal scrollbar on the table.
            name = f"`{field}`"
            if config.get("required"):
                name += " **(required)**"
            rows.append(
                [
                    name,
                    cell(field_strings.get("name")),
                    cell(selector_summary(config.get("selector"))),
                    cell(field_strings.get("description")),
                ]
            )
        if rows:
            lines += _table(["Field", "Label", "Selector", "Description"], rows)
        else:
            lines += ["Takes no fields.", ""]
    return lines


def render_events(sources: Sources) -> list[str]:
    """The event catalog, then one payload table per shape they share."""
    surface = sources.surface
    fired = [spec for spec in surface.EVENTS if spec.direction == "fired"]
    listened = [spec for spec in surface.EVENTS if spec.direction == "listened"]

    lines = [
        "## Events",
        "",
        "The integration fires a bus event for every observable state change.",
        "Names follow `example_integration_<noun>_<verb>`. For when each one",
        "fires in context, and worked automations, see the",
        f"[events guide]({_SITE}/developer/events).",
        "",
        *_table(
            ["Event", "Fires when", "Payload", "Adds"],
            [
                [
                    f"`{spec.name}`",
                    cell(spec.summary),
                    f"[{spec.payload}](#{spec.payload}-payload)"
                    if spec.payload != "none"
                    else "none",
                    ", ".join(f"`{f.name}`" for f in spec.extra),
                ]
                for spec in fired
            ],
        ),
    ]

    if listened:
        lines += [
            "The integration also listens for events it does not own:",
            "",
            *_table(
                ["Event", "Reaction"],
                [[f"`{spec.name}`", cell(spec.summary)] for spec in listened],
            ),
        ]

    lines += [
        "### Payloads",
        "",
        "Events sharing a payload shape are interchangeable in one automation",
        "template. Per-event additions from the table above merge onto these.",
        "",
    ]
    for shape, fields in surface.PAYLOAD_SPINES.items():
        carriers = surface.events_by_payload(shape)
        lines += [
            f"#### {shape.capitalize()} payload",
            "",
            "Carried by " + ", ".join(f"`{spec.name}`" for spec in carriers) + ".",
            "",
            *_fields_table(fields),
        ]
    return lines


def render_device_triggers(sources: Sources) -> list[str]:
    """The device triggers, or nothing when the integration declares none."""
    surface, _, strings = sources
    if not surface.DEVICE_TRIGGERS:
        return []
    labels = strings.get("device_automation", {}).get("trigger_type", {})
    return [
        "## Device triggers",
        "",
        "On a device of this integration, *Add automation → When* offers these, so",
        "an automation can be built without knowing any event name. They are the",
        "same events as above, filtered to that one device.",
        "",
        *_table(
            ["Trigger", "Shown as", "Event", "Offered on"],
            [
                [
                    f"`{spec.type}`",
                    cell(labels.get(spec.type)),
                    f"`{spec.event}`",
                    cell(spec.scope),
                ]
                for spec in surface.DEVICE_TRIGGERS
            ],
        ),
    ]


def render_entities(sources: Sources) -> list[str]:
    surface, _, strings = sources
    lines = [
        "## Entities",
        "",
        "The integration's state is readable as ordinary entities, so most",
        "automations never need to call an action to find something out.",
        "",
    ]
    for spec in surface.ENTITY_PLATFORMS:
        entity_strings = strings.get("entity", {}).get(spec.platform, {})
        named = ", ".join(
            f"`{cell(entity_strings.get(key, {}).get('name', key))}` (`{key}`)"
            for key in spec.translation_keys
        )
        lines += [
            f"### `{spec.platform}`",
            "",
            (
                f"Entities: {named}."
                if named
                else "One list entity for the whole integration, named directly."
            ),
            "",
        ]
        if spec.attributes:
            lines += ["State attributes:", "", *_fields_table(spec.attributes)]
    return lines


def render_options(sources: Sources) -> list[str]:
    """The config entry options, or nothing when the integration declares none."""
    surface, _, strings = sources
    if not surface.OPTIONS:
        return []
    form = strings.get("options", {}).get("step", {}).get("init", {})
    labels = form.get("data", {})
    helps = form.get("data_description", {})
    return [
        "## Config entry options",
        "",
        "Readable and writable through the `set_options` action. The ones marked",
        "*Configure dialog* also appear on the integration's options form; the rest",
        "are edited in the panel.",
        "",
        *_table(
            ["Option", "Label", "Where", "Notes"],
            [
                [
                    f"`{spec.key}`",
                    cell(labels.get(spec.key)),
                    "Configure dialog" if spec.in_flow else "Panel",
                    cell(helps.get(spec.key)),
                ]
                for spec in surface.OPTIONS
            ],
        ),
    ]


def render_errors(sources: Sources) -> list[str]:
    _, _, strings = sources
    return [
        "## Errors",
        "",
        "A rejected action raises a localized Home Assistant error. The key is",
        "stable; the message shown is in the user's language.",
        "",
        *_table(
            ["Key", "English message"],
            [
                [f"`{key}`", cell(value.get("message"))]
                for key, value in sorted(strings.get("exceptions", {}).items())
            ],
        ),
    ]


def render(sources: Sources) -> str:
    """Return the complete page, frontmatter included."""
    lines = [
        "---",
        f"title: {json.dumps(PAGE_TITLE)}",
        f"sidebar_label: {json.dumps(PAGE_TITLE)}",
        f"sidebar_position: {PAGE_POSITION}",
        # CommonMark, not MDX: selector summaries and payload types contain literal
        # braces and angle brackets that MDX would try to parse as JSX.
        "format: md",
        "---",
        "",
        _BANNER,
        "",
        "Every surface an integration or automation can build on, generated from",
        "the shipping code. Labels and descriptions are the same strings Home",
        "Assistant shows in its own dialogs, so this page and the UI never",
        "disagree.",
        "",
        "New to this? Start with the "
        f"[integration guide]({_SITE}/developer/integrating), which walks through",
        "calling a service and reacting to its event.",
        "",
        *render_surface_coverage(sources),
        *render_services(sources),
        *render_events(sources),
        *render_device_triggers(sources),
        *render_entities(sources),
        *render_options(sources),
        *render_errors(sources),
    ]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT, help="where to write the page"
    )
    parser.add_argument(
        "--stdout", action="store_true", help="print the page instead of writing it"
    )
    args = parser.parse_args(argv)

    page = render(load_sources())
    if args.stdout:
        sys.stdout.write(page)
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(page, encoding="utf-8")
    # Relative to the repo root when it sits inside it, which is the readable form
    # for the usual npm-run-sync invocation from website/; absolute otherwise.
    print(f"[generate-api-docs] wrote {os.path.relpath(args.out, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
