import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// User Guide. `intro` is hand-authored; the per-topic pages under docs/guide/ are
// generated from README.md by scripts/sync-docs.mjs and picked up automatically.
const sidebars: SidebarsConfig = {
  userSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guide',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
    'release-notes',
  ],
};

export default sidebars;
