import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Developer Guide — the pages under developer/ are generated from docs/*.md by
// scripts/sync-docs.mjs and ordered via their sidebar_position frontmatter.
const sidebars: SidebarsConfig = {
  developerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
